name: Deploy Lambdas

on:
  push:
    branches:
      - main

jobs:
  deploy_lambdas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Detect Modified Lambdas
        id: detect_changes
        run: |
          # Ensure at least one commit exists before using HEAD^
          if git rev-parse --verify HEAD^ &>/dev/null; then
            MODIFIED_LAMBDAS=$(git diff --name-only HEAD^ HEAD | grep '^lambdas/' | awk -F/ '{print $2}' | uniq)
          else
            MODIFIED_LAMBDAS=$(git ls-files 'lambdas/' | awk -F/ '{print $2}' | uniq)
          fi
          echo "Modified Lambdas: $MODIFIED_LAMBDAS"
          
          # Save modified Lambdas to a file
          echo "$MODIFIED_LAMBDAS" > modified_lambdas.txt

      - name: Deploy Modified Lambdas
        if: success() && steps.detect_changes.outputs.modified != ''
        run: |
          # Read the modified Lambdas from the file
          while read -r lambda; do
            echo "Deploying Lambda: $lambda"
            cd lambdas/$lambda
            
            # Install dependencies for the Lambda
            npm ci --only=prod

            # Zip the Lambda folder
            zip -r ../../$lambda.zip . 
            
            # Deploy to AWS Lambda
            aws lambda update-function-code \
              --function-name $lambda \
              --zip-file fileb://../../$lambda.zip
            cd ../..
          done < modified_lambdas.txt
