name: Deploy Lambdas

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to observe'
        required: true
        default: 'main'
  push:
    branches:
      - main
    paths:
      - 'lambdas/**'

jobs:
  deploy_lambdas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Detect Modified Lambdas
        id: detect_changes
        run: |
          echo "Detecting modified Lambda folders..."
          # Check if there's a previous commit
          if git rev-parse --verify HEAD^ &>/dev/null; then
            MODIFIED_LAMBDAS=$(git diff --name-only HEAD^ HEAD | grep '^lambdas/' | awk -F/ '{print $2}' | sort | uniq)
          else
            MODIFIED_LAMBDAS=$(git ls-files 'lambdas/' | awk -F/ '{print $2}' | sort | uniq)
          fi

          echo "Modified Lambdas detected:"
          echo "$MODIFIED_LAMBDAS"

          # Debug: Print each Lambda detected
          for lambda in $MODIFIED_LAMBDAS; do
            echo "Detected Lambda folder: $lambda"
          done

          # Save modified Lambdas to file
          echo "$MODIFIED_LAMBDAS" > modified_lambdas.txt
          cat modified_lambdas.txt

          # Set output for next steps
          echo "::set-output name=modified::$MODIFIED_LAMBDAS"

      - name: Check if Modified Lambdas Exist
        run: |
          echo "Modified Lambdas Output: ${{ steps.detect_changes.outputs.modified }}"
          if [ -s modified_lambdas.txt ]; then
            echo "Modified Lambdas file contents:"
            cat modified_lambdas.txt
          else
            echo "No modified Lambdas found."
            exit 0

      - name: Deploy Modified Lambdas
        if: steps.detect_changes.outputs.modified != ''
        run: |
          echo "Deploying modified Lambdas..."
          while IFS= read -r lambda; do
            echo "Processing Lambda: $lambda"

            # Check if Lambda folder exists
            if [ ! -d "lambdas/$lambda" ]; then
              echo "Warning: Folder 'lambdas/$lambda' does not exist. Skipping..."
              continue
            fi

            echo "Deploying Lambda: $lambda"
            cd lambdas/$lambda

            # Install dependencies
            echo "Installing dependencies for $lambda..."
            npm ci --only=prod

            # Zip Lambda folder
            echo "Creating deployment package for $lambda..."
            zip -r ../../$lambda.zip .

            # Deploy to AWS Lambda
            echo "Deploying $lambda to AWS..."
            aws lambda update-function-code \
              --function-name $lambda \
              --zip-file fileb://../../$lambda.zip

            echo "Successfully deployed $lambda."
            cd ../..
          done < modified_lambdas.txt
