name: Deploy Lambdas

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to observe'
        required: true
        default: 'main'
  push:
    branches:
      - main
    paths:
      - 'lambdas/**'

jobs:
  deploy_lambdas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Detect Modified Lambdas
        id: detect_changes
        run: |
          if git rev-parse --verify HEAD^ &>/dev/null; then
            MODIFIED_LAMBDAS=$(git diff --name-only HEAD^ HEAD | grep '^lambdas/' | awk -F/ '{print $2}' | sort | uniq)
          else
            MODIFIED_LAMBDAS=$(git ls-files 'lambdas/' | awk -F/ '{print $2}' | sort | uniq)
          fi
          echo "Modified Lambdas: $MODIFIED_LAMBDAS"

          # Save modified Lambdas to a file
          echo "$MODIFIED_LAMBDAS" > modified_lambdas.txt

          # Use environment files instead of set-output (deprecated)
          echo "modified=$MODIFIED_LAMBDAS" >> $GITHUB_ENV

      - name: Check if Modified Lambdas Exist
        run: |
          echo "Modified Lambdas: ${{ env.modified }}"
          cat modified_lambdas.txt

      - name: Deploy Modified Lambdas
        if: env.modified != ''
        run: |
          if [ -s modified_lambdas.txt ]; then
            echo "Deploying modified Lambdas..."
            while IFS= read -r lambda; do
              echo "Deploying Lambda: $lambda"
              cd lambdas/$lambda

              # Install dependencies
              npm ci --only=prod

              # Zip the Lambda folder
              zip -r ../../$lambda.zip .

              # Deploy to AWS Lambda
              aws lambda update-function-code \
                --function-name $lambda \
                --zip-file fileb://../../$lambda.zip
              cd ../..
            done < modified_lambdas.txt
          else
            echo "No modified Lambdas to deploy."
          fi
